name: CI/CD to Heroku

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps + smoke check
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python - << 'PY'
        import os
        assert os.path.exists("app/model.pkl"), "Missing app/model.pkl"
        assert os.path.exists("app/schema.json"), "Missing app/schema.json"
        print("Artifacts present.")
        PY

    # Install Heroku CLI (official install script)
    - name: Install Heroku CLI
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh

    # Authenticate Heroku by writing ~/.netrc using your repo secrets
    - name: Heroku auth
      env:
        HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        cat > ~/.netrc <<EOF
        machine api.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        machine git.heroku.com
          login $HEROKU_EMAIL
          password $HEROKU_API_KEY
        EOF
        chmod 600 ~/.netrc
        heroku auth:whoami

    - name: Set Heroku git remote
      run: |
        heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

    - name: Deploy (git push to Heroku)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git push heroku HEAD:main -f
