name: CI/CD to Heroku

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    # --- SINGLE checkout, full history ---
    - name: Checkout full history
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # sanity: if somehow shallow, unshallow it
    - name: Ensure repo is not shallow
      run: |
        if git rev-parse --is-shallow-repository; then
          git fetch --prune --unshallow
        fi
        git rev-parse --is-shallow-repository || true
        git log --oneline -n 3 || true

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install deps + smoke check
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python - << 'PY'
        import os
        assert os.path.exists("app/model.pkl"), "Missing app/model.pkl"
        assert os.path.exists("app/schema.json"), "Missing app/schema.json"
        print("Artifacts present.")
        PY

    - name: Validate secrets
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        [ -n "$HEROKU_API_KEY" ] || (echo "HEROKU_API_KEY is not set" && exit 1)
        [ -n "$HEROKU_APP_NAME" ] || (echo "HEROKU_APP_NAME is not set" && exit 1)

    - name: Deploy (git push to Heroku)
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        # add or reset the heroku remote
        git remote remove heroku 2>/dev/null || true
        git remote add heroku "https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git"
        # push with full history (now allowed)
        git push heroku HEAD:main -f

    - name: Ping app
      env:
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      run: |
        sleep 10
        curl -sSf "https://$HEROKU_APP_NAME.herokuapp.com/" > /dev/null
